on: push
jobs:
  first-job:
    runs-on: macOS-latest
    # container: node:18.x # use to this to run on specific node version by specifying the exact version as 18.0.6
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node app.js